### ISSUE TITLE
.gitignore 파일 추가 필요

### ISSUE THREAD

**Issue by harrydrippin** [ngEPL/ngEPL_mobile#1]
유저 설정 파일(`.userprefs`)이 그대로 올라오고 있음, `.gitignore` 파일을 추가해야 함.
추가할 때 .DS_Store와 같은 파일 시스템 관리용 파일도 차단해야 할 듯.

### 예시
```
#.gitignore
.DS_Store
newEPL.userprefs
```

**Comment by choms46** [comment]
모든 파일 재 업로드 예정입니다~
